run-name: Deploy by @${{ github.actor }}

on:
  push:
    branches: ["main"]
    
jobs:

  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H onoicrm.com >> ~/.ssh/known_hosts

      - name: Make fake package-lock for install node
        run: touch package-lock.json
      - name: Install nodejs 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "npm"

      - name: Build front
        run: cd ./Onoicrm.Front && npm ci && npm run build

      - name: Copy front to remote
        run: |
          cd ./Onoicrm.Front
          rsync -a --delete ./dist/ root@onoicrm.com:/app/www/front
  

  admin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H onoicrm.com >> ~/.ssh/known_hosts

      - name: Make fake package-lock for install node
        run: touch package-lock.json
      - name: Install nodejs 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: "npm"
      - name: Build admin
        run: cd ./Onoicrm.Admin && npm ci && npm run build
      - name: Copy admin to remote
        run: |
          cd ./Onoicrm.Admin
          rsync -a --delete ./dist/ root@onoicrm.com:/app/www/admin

  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H onoicrm.com >> ~/.ssh/known_hosts

      - name: Setup dotnet "7.0.x"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.0.x"

      - name: Build Code
        run: dotnet restore "Onoicrm.Api/Onoicrm.Api.csproj" && dotnet build "Onoicrm.Api/Onoicrm.Api.csproj" -c Release -o ./build && dotnet publish "Onoicrm.Api/Onoicrm.Api.csproj" -c Release -o ./publish

      - name: Copy code
        run: rsync -a --delete ./publish/ root@onoicrm.com:/app/www/api

  infrastructure:
    runs-on: ubuntu-latest
    needs: [front, api, admin]
    steps:
      - uses: actions/checkout@v3
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H onoicrm.com >> ~/.ssh/known_hosts
          
      - name: Copy configs
        run: rsync -a ./Deploy/ root@onoicrm.com:/app/infrastructure
      - name: restart infrastructure
        run: ssh root@onoicrm.com "cd /app/infrastructure && docker compose down && docker compose up -d"